name: push

on:
  push:
    branches:
      - rewrite
  pull_request:
    branches:
      - rewrite

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
  gofumpt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go install mvdan.cc/gofumpt@latest
          if gofumpt -l -e . | grep '^' -q; then exit 1; fi
  test:
    runs-on: ubuntu-latest
    needs: [commitlint, golangci-lint, gofumpt]
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out | grep -E '^total:.*100.0%$'
  build:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go build -v ./...
