name: push

on:
  push:
    branches:
      - rewrite
  pull_request:
    branches:
      - rewrite

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: golangci/golangci-lint-action@v3
      - uses: wagoid/commitlint-github-action@v5
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go test -v ./...
      - run: go build -v ./...
