name: scrape

on:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: rewrite
      - uses: actions/setup-go@v3
      - run: |
          go test -v -run ^TestScraping$ ./...
        env:
          TEST_SCRAPING: true
