name: push

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: |
          go test -v -timeout 30s ./...
        env:
          XDG_MUSIC_DIR: /tmp
  build:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: |
          go mod download
          go install mvdan.cc/garble@latest
          for os in linux darwin windows; do
            for arch in arm64 amd64; do
              fname="spotitube-${os}-${arch}"
              if test "${os}" = "windows"; then
                fname="${fname}.exe"
              fi
              echo "building $fname..."
              GOOS=$os GOARCH=$arch CGO_ENABLED=0 garble -literals -tiny -seed=random build -ldflags="
                -X github.com/streambinder/spotitube/spotify.fallbackSpotifyID=$SPOTIFY_ID
                -X github.com/streambinder/spotitube/spotify.fallbackSpotifyKey=$SPOTIFY_KEY
                -X github.com/streambinder/spotitube/lyrics.fallbackGeniusToken=$GENIUS_TOKEN
              " -o "$fname"
            done
          done
        env:
          SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
          SPOTIFY_KEY: ${{ secrets.SPOTIFY_KEY }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_ACTIONS_SPOTITUBE }}
          files: ./spotitube-*
          draft: false
          prerelease: false
  docker:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          secrets: |
            SPOTIFY_ID=${{ secrets.SPOTIFY_ID }}
            SPOTIFY_KEY=${{ secrets.SPOTIFY_KEY }}
            GENIUS_TOKEN=${{ secrets.GENIUS_TOKEN }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ghcr.io/streambinder/spotitube:${{ github.ref_name }}
